# Generated by Django 3.0.6 on 2020-05-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('CompanyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentapi.Company')),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
