# Generated by Django 3.0.6 on 2020-05-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentapi', '0002_auto_20200525_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='CompanyId',
            new_name='company',
        ),
    ]
