# Generated by Django 3.0.6 on 2020-05-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentapi', '0004_job_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='number',
        ),
    ]
